/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    403: typeof import("./../components/errorCom/403.vue")["default"];
    404: typeof import("./../components/errorCom/404.vue")["default"];
    500: typeof import("./../components/errorCom/500.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAutocomplete: typeof import("element-plus/es")["ElAutocomplete"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBacktop: typeof import("element-plus/es")["ElBacktop"];
    ElBadge: typeof import("element-plus/es")["ElBadge"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElFooter: typeof import("element-plus/es")["ElFooter"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSpace: typeof import("element-plus/es")["ElSpace"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    Footer: typeof import("./../layouts/components/Footer/index.vue")["default"];
    Header: typeof import("./../layouts/components/Header/index.vue")["default"];
    IEpEdit: typeof import("~icons/ep/edit")["default"];
    IEpLock: typeof import("~icons/ep/lock")["default"];
    IEpSearch: typeof import("~icons/ep/search")["default"];
    IEpSwitchButton: typeof import("~icons/ep/switch-button")["default"];
    IEpUser: typeof import("~icons/ep/user")["default"];
    Language: typeof import("./../layouts/components/Header/components/language.vue")["default"];
    LoginForm: typeof import("./../views/login/components/loginForm.vue")["default"];
    Main: typeof import("./../layouts/components/Main/index.vue")["default"];
    Notice: typeof import("./../layouts/components/Header/components/notice.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Screen: typeof import("./../layouts/components/Header/components/screen.vue")["default"];
    Search: typeof import("./../layouts/components/Header/components/search.vue")["default"];
    SIdentify: typeof import("./../components/SIdentify/index.vue")["default"];
    SubMenu: typeof import("./../layouts/components/Menu/SubMenu.vue")["default"];
    SvgIcon: typeof import("./../components/SvgIcon/index.vue")["default"];
    SwitchDark: typeof import("./../components/SwitchDark/index.vue")["default"];
    Tabs: typeof import("./../layouts/components/Tabs/index.vue")["default"];
    User: typeof import("./../layouts/components/Header/components/user.vue")["default"];
    UserDrawer: typeof import("./../layouts/components/components/userDrawer.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import("element-plus/es")["ElInfiniteScroll"];
  }
}
